_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 105
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.6
            "6": 4.45.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
mode:
    value: zero_shot
